USE [master]
GO

/****** Object:  Database [Bookish]    Script Date: 14/11/2018 14:40:00 ******/
CREATE DATABASE [Bookish]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Bookish', FILENAME = N'C:\Work\Training\Bookish\Bookish.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Bookish_log', FILENAME = N'C:\Work\Training\Bookish\Bookish_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Bookish] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Bookish].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Bookish] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Bookish] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Bookish] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Bookish] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Bookish] SET ARITHABORT OFF 
GO

ALTER DATABASE [Bookish] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Bookish] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Bookish] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Bookish] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Bookish] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Bookish] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Bookish] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Bookish] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Bookish] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Bookish] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Bookish] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Bookish] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Bookish] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Bookish] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Bookish] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Bookish] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Bookish] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Bookish] SET RECOVERY FULL 
GO

ALTER DATABASE [Bookish] SET  MULTI_USER 
GO

ALTER DATABASE [Bookish] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Bookish] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Bookish] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Bookish] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Bookish] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Bookish] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Bookish] SET  READ_WRITE 
GO


