USE [Bookish]
GO

/****** Object:  Table [dbo].[Author]    Script Date: 14/11/2018 14:41:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Author](
	[AuthorID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](40) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[AuthorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[Book](
	[BookID] [int] IDENTITY(1,1) NOT NULL,
	[Title] [varchar](50) NOT NULL,
	[ISBN] [varchar](13) NOT NULL,
	[Author] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[BookID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Book]  WITH CHECK ADD  CONSTRAINT [fk_book_author] FOREIGN KEY([Author])
REFERENCES [dbo].[Author] ([AuthorID])
GO

ALTER TABLE [dbo].[Book] CHECK CONSTRAINT [fk_book_author]
GO


CREATE TABLE [dbo].[Copy](
	[CopyID] [int] IDENTITY(1,1) NOT NULL,
	[Book] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CopyID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Copy]  WITH CHECK ADD FOREIGN KEY([Book])
REFERENCES [dbo].[Book] ([BookID])
GO


CREATE TABLE [dbo].[CheckedOut](
	[UserID] [int] NOT NULL,
	[Copy] [int] NOT NULL,
	[DueDate] [date] NOT NULL,
 CONSTRAINT [pk_checkedout] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC,
	[Copy] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CheckedOut]  WITH CHECK ADD FOREIGN KEY([Copy])
REFERENCES [dbo].[Copy] ([CopyID])
GO